# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-19 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('crm', '0002_auto_20181105_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.ManyToManyField(to='rbac.Role', verbose_name='对应角色'),
        ),
    ]
