# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-21 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20181119_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, verbose_name='主机名')),
                ('hostpwd', models.CharField(max_length=64, verbose_name='主机密码')),
                ('hostaddr', models.CharField(max_length=64, verbose_name='主机地址')),
                ('business', models.CharField(max_length=64, verbose_name='对应业务')),
            ],
        ),
    ]
