# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-19 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='描述信息')),
                ('url', models.CharField(max_length=256, verbose_name='URL')),
                ('alias_url', models.CharField(max_length=64, verbose_name='URL别名')),
                ('is_menu', models.BooleanField(verbose_name='是否是菜单')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='角色')),
                ('permission', models.ManyToManyField(to='rbac.Permissions', verbose_name='拥有的权限')),
            ],
        ),
    ]
