# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20181119_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='icon',
            field=models.CharField(default='map-o', max_length=64, verbose_name='图标'),
            preserve_default=False,
        ),
    ]
