# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-21 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_permissions_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='icon',
        ),
    ]
