# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-21 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_remove_permissions_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='icon',
            field=models.CharField(max_length=64, null=True, verbose_name='图标'),
        ),
    ]
