# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_permissions_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='菜单')),
            ],
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='is_menu',
        ),
        migrations.AddField(
            model_name='permissions',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='菜单'),
        ),
    ]
