# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20181127_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(max_length=64, null=True, verbose_name='图标'),
        ),
    ]
