# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_menu_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Permissions', verbose_name='父权限'),
        ),
    ]
